# Generated by Django 5.0.2 on 2024-03-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalreg',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='hospitalreg',
            name='Token',
            field=models.IntegerField(null=True),
        ),
    ]
